"""
Django settings for orders project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

import os

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.redis import RedisIntegration

import django_filters
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'baton',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'social_django',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'drf_spectacular',
    'backend',
    'imagekit',
    'baton.autodiscover',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT аутентификация
        'rest_framework.authentication.SessionAuthentication',         # Сессионная аутентификация для браузера
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # Разрешения по умолчанию
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',  # Фильтрация
        'rest_framework.filters.SearchFilter',                # Поиск
        'rest_framework.filters.OrderingFilter',              # Сортировка
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',  # Пагинация
    'PAGE_SIZE': 10,  # Размер страницы
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Throttling settings
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',      # Для анонимных пользователей
        'user': '1000/day',     # Для аутентифицированных
        'register': '3/hour',   # Регистрация - 3 в час
        'login': '10/minute',   # Логин - 10 в минуту
        'verify_email': '5/hour', # Подтверждение email - 5 в час
        'partner_update': '10/hour', # Загрузка прайса - 10 в час
    },
}

ROOT_URLCONF = 'orders.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
            ],
        },
    },
]

WSGI_APPLICATION = 'orders.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'CHECK_REVOKE_TOKEN': True,
    'REVOKE_TOKEN_CLAIM': 'revoke',
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Custom User Model
AUTH_USER_MODEL = 'backend.CustomUser'

# Default auto field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email settings
if DEBUG:
    # Режим разработки
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    print("Email отправка в консоль (режим разработки)")
else:
    # Режим продакшена
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

# Celery settings
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379')

# Сериализация
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Таймауты для email задач (SMTP может быть медленным)
CELERY_TASK_TIME_LIMIT = 5 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 4 * 60

# Хранение результатов (email не требует долгого хранения)
CELERY_RESULT_EXPIRES = 1800  # 30 минут

# Настройки для продакшена
if not DEBUG:
    # Оптимизация для email задач
    CELERY_WORKER_PREFETCH_MULTIPLIER = 1   # По одной задаче за раз для email
    CELERY_WORKER_MAX_TASKS_PER_CHILD = 100  # Перезапуск после 100 email

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Orders API',
    'DESCRIPTION': 'API для управления заказами, товарами и пользователями',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Теги для группировки эндпоинтов
    'TAGS': [
        {'name': 'auth', 'description': 'Аутентификация и авторизация'},
        {'name': 'products', 'description': 'Товары и категории'},
        {'name': 'cart', 'description': 'Корзина'},
        {'name': 'orders', 'description': 'Заказы'},
        {'name': 'contacts', 'description': 'Контактные данные'},
        {'name': 'partners', 'description': 'Партнёры и поставщики'},
    ],
    # Компоненты безопасности
    'SECURITY': [
        {
            'Bearer': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    ],
    # Дополнительные настройки
    'COMPONENT_SPLIT_REQUEST': True,
    'ENUM_NAME_OVERRIDES': {
        'OrderStatus': 'backend.models.Order.StatusChoices',
    },
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://localhost:6379/1'),
    }
}

AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.vk.VKOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]

# Social Auth Settings
SOCIAL_AUTH_URL_NAMESPACE = 'social'

# Pipeline - процесс обработки авторизации
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'backend.social_pipeline.create_jwt_tokens'
)

# Стратегия
SOCIAL_AUTH_STRATEGY = 'social_django.strategy.DjangoStrategy'
SOCIAL_AUTH_STORAGE = 'social_django.models.DjangoStorage'

# Настройки для конкретных провайдеров
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('GOOGLE_OAUTH2_SECRET')
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['email', 'profile']
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/api/auth/social/token/'
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/api/auth/social/token/'


# В конец файла
BATON = {
    'SITE_TITLE': 'Orders Admin',
    'SITE_HEADER': 'Orders Administration',
    'INDEX_TITLE': 'Панель управления',
    'COPYRIGHT': 'Orders © 2026',
    'CONFIRM_UNSAVED_CHANGES': True,
    'SHOW_MULTIPART_UPLOADING': True,
    'ENABLE_IMAGES_PREVIEW': True,
    'CHANGELIST_FILTERS_IN_MODAL': True,
    'CHANGELIST_FILTERS_FORM': True,
    'MESSAGES_TOASTS': True,
    'GRAVATAR_ENABLED': True,
    'GRAVATAR_DEFAULT_IMG': 'retro',
    'MENU': (
        {
            'type': 'title',
            'label': 'Пользователи',
            'apps': ('backend',),
        },
        {
            'type': 'app',
            'name': 'backend',
            'label': 'Пользователи и магазины',
            'models': (
                {'name': 'customuser', 'label': 'Пользователи'},
                {'name': 'userrole', 'label': 'Роли'},
                {'name': 'shop', 'label': 'Магазины'},
                {'name': 'shopemployee', 'label': 'Сотрудники'},
            ),
        },
        {
            'type': 'title',
            'label': 'Каталог товаров',
            'apps': ('backend',),
        },
        {
            'type': 'app',
            'name': 'backend',
            'label': 'Каталог',
            'models': (
                {'name': 'category', 'label': 'Категории'},
                {'name': 'product', 'label': 'Товары'},
                {'name': 'productinfo', 'label': 'Товары в магазинах'},
                {'name': 'productimage', 'label': 'Изображения'},
                {'name': 'parameter', 'label': 'Параметры'},
                {'name': 'productparameter', 'label': 'Значения параметров'},
            ),
        },
        {
            'type': 'title',
            'label': 'Заказы и контакты',
            'apps': ('backend',),
        },
        {
            'type': 'app',
            'name': 'backend',
            'label': 'Заказы',
            'models': (
                {'name': 'order', 'label': 'Заказы'},
                {'name': 'orderitem', 'label': 'Позиции заказов'},
                {'name': 'contact', 'label': 'Контакты'},
            ),
        },
        {
            'type': 'title',
            'label': 'Система',
            'apps': ('auth', 'social_django'),
        },
        {
            'type': 'app',
            'name': 'auth',
            'label': 'Группы доступа',
            'models': (
                {'name': 'group', 'label': 'Группы'},
            ),
        },
    ),
}

# Настройки для django-imagekit
IMAGEKIT_CACHEFILE_BACKEND = 'imagekit.cachefiles.backends.Default'
IMAGEKIT_DEFAULT_CACHEFILE_STRATEGY = 'imagekit.cachefiles.strategies.Optimistic'
IMAGEKIT_SPEC_CACHEFILE_NAMER = 'imagekit.cachefiles.namers.source_name_as_path'

# Sentry (self-hosted)
SENTRY_DSN = os.getenv('SENTRY_DSN')

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
            RedisIntegration(),
        ],
        traces_sample_rate=1.0 if DEBUG else 0.2,
        send_default_pii=True,
        environment='development' if DEBUG else 'production',
    )
