# Generated by Django 6.0.3 on 2026-04-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Список категорий'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ['name'], 'verbose_name': 'Наименование параметра', 'verbose_name_plural': 'Список параметров'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Список продуктов'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['name'], 'verbose_name': 'Магазин', 'verbose_name_plural': 'Список магазинов'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='building',
            field=models.CharField(blank=True, max_length=40, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='structure',
            field=models.CharField(blank=True, max_length=40, verbose_name='Строение'),
        ),
    ]
